#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "./run api|web"
elif [ $1 == "api" ]; then
  cargo run -p wu-api
elif [ $1 == "web" ]; then
  wasm-pack build --dev --no-typescript -t web -d ../wu-app/pkg wu-web
else
  echo "./run api|web"
fi
